services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"

  web:
    build: .
    container_name: django_app
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "until nc -z db 3306; do sleep 1; done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

volumes:
  mariadb_data:
