services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerceDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

  # Django service
  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: ecommerceDB
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "until nc -z db 3306; do sleep 1; done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

volumes:
  mariadb_data:
