# Generated by Django 4.2.20 on 2025-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('main_image', models.ImageField(default='products/default.jpg', max_length=255, upload_to='products')),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
